#!/bin/sh
# https://github.com/chibat/deno-wrapper
# Copyright (c) 2023 Tomofumi Chiba
# MIT License
set -e

# https://manpages.ubuntu.com/manpages/kinetic/en/man1/chronic.1.html
chronic() (
  set +e
  output=$($@ 2>&1)
  exit_code=$?
  set -e
  if [ "$exit_code" -ne 0 ]; then
    echo "$output" >&2
  fi
  return "$exit_code"
)

if [ ! -d .deno ]; then
    # https://deno.com/manual/getting_started/installation
    export DENO_INSTALL=.deno
    curl -fsSL https://deno.land/x/install/install.sh | chronic sh -s "v{{version}}"
fi

# https://github.com/denoland/deno_install/blob/master/install.sh#L53
export DENO_INSTALL=.deno
export PATH="$DENO_INSTALL/bin:$PATH"

exec .deno/bin/deno "$@"
